### ISSUE TITLE
Error_while executing the code

### ISSUE THREAD

**Issue by anvcse562** [mmguero/cleanvid#1]
I have tried installing the delegator from delegator.py.But, I still end up with the below error. 

would you please assist me. My python version is 2.7

AttributeError: 'module' object has no attribute 'run'

Traceback (most recent call last):
  File "cleanvid.py", line 162, in <module>
    cleaner.MultiplexCleanVideo()
  File "cleanvid.py", line 124, in MultiplexCleanVideo
    ffmpegResult = delegator.run("ffmpeg -y -i \"" + self.inputVidFileSpec + "\"" + \
AttributeError: 'module' object has no attribute 'run'

**Comment by mmguero** [comment]
Hmm... that is the error I was getting before I had delegator.py installed correctly. Here's my configuration:

```
$ python --version
Python 2.7.13

$ pip show delegator.py
Name: delegator.py
Version: 0.1.0
Summary: Subprocesses for Humans 2.0.
Home-page: https://github.com/kennethreitz/delegator
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: pexpect
```

I think there is a different pip module called just `delegator`, maybe there is a conflict there?
```
$ pip show delegator
```
That should not show any results. If it does, do `pip remove delegator` and then `pip install delegator.py`

**Comment by anvcse562** [comment]
Thanks for the quick turnaround. I have downloaded the delegator.py and it is working fine. what are the video formats that are supportive here

**Comment by mmguero** [comment]
As far as the input video goes, it should work with any format ffmpeg supports. The output video codec is the same as the input. The output audio codec is created with the `-c:a aac -ac 2 -ab 224k -ar 44100` flags

I'm not a Mac guy, but I'm sure one of these links could help:

- https://www.ffmpeg.org/download.html#build-mac
- https://evermeet.cx/ffmpeg/
- https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/Installing-ffmpeg-on-Mac-OS-X
- https://youtu.be/qu7tvO-Pmko

Good luck!

**Comment by anvcse562** [comment]
Thanks again. It is working now. I saw the muting option that is listed on the script. However, It is muting the entire sentence instead of the duration of which the bad word is spoken.

**Comment by mmguero** [comment]
Yes, it mutes the audio for the duration of that one line/sentence in the subtitles file. It can't get any more accurate than that with the method I'm using to do it.
