### ISSUE TITLE
Verbose Mode / Embedding Comments in EDL Files

### ISSUE THREAD

**Issue by hendursaga** [mmguero/cleanvid#11]
Sometimes I'd like to tweak my EDL files, and while this tool can output a generally great starting point, it's cumbersome trying to figure out which words it's trying to mute on. I've tested on Debian Stable's MPlayer (1.4) and it appears it ignores comments or in fact anything after the 3rd field. See [this line](https://github.com/sherpya/MPlayer/blob/4cc95fdf90021978958a36c72dd52bf97868049d/edl.c#L96) for reference. For Kodi, which I don't use, it [allows comments on their own lines](https://kodi.wiki/view/Edit_decision_list#MPlayer_EDL) starting with `##`. Note I haven't checked if Kodi disregards anything past the 3rd field.

I propose a command-line flag (or even default behavior!) embedding within the EDL file information on what word(s) it is censoring at such-and-such a timestamp.

**Comment by mmguero** [comment]
Thanks for the suggestion, I think that's doable. I'll check it out.

**Comment by mmguero** [comment]
What I've decided to do instead here is add a `--json` option that will dump information about the input and output parameters as well as the edits to a JSON file. You can then use that JSON file to do whatever you want, and I don't need to worry about multiple EDL formats that might handle comments differently.
