### ISSUE TITLE
Multilingual Filtering

### ISSUE THREAD

**Issue by hendursaga** [mmguero/cleanvid#12]
The `swears.txt` file is English-only, but I like watching foreign-language films, so a multilingual dataset of bad words would be great. [LDNOOBW](https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words) by Shutterstock is probably the best dataset I've come across that could do the job.

Seeing as we already have a `--lang` flag, perhaps we could extend it to select which language(s) to search for bad words? The one problem would be when some video has more than one language in it - thoughts?

**Comment by mmguero** [comment]
Thanks for the suggestion! I'll check it out.

**Comment by mmguero** [comment]
Apologies, I don't see myself spending time on this. A well-considered PR would be accepted.
