### ISSUE TITLE
Mute master pc volume app

### ISSUE THREAD

**Issue by cybernate321** [mmguero/cleanvid#14]
Hi I'm sorry if this is in the wrong place but I can't see any other way of contacting you. Thank you for creating software to remove profanities. 
I currently use an EDL file along with Kodi to mute the swearing in videos but this is limited to videos I own. I would love to be able to play tv and films from streaming platforms such as Amazon and Apple TV and mute the swearing on the fly. The only way I can think of that this could be done is to have a simple timer app that can import an EDL file for the timings and can be started at the same time as the streaming video. The app would be designed to mute the master pc volume based upon the timings.
I'm not a programmer so I'm not going to attempt this myself but wondered if you might be up for the challenge or could direct me to the right website where I could request this?

Regards

Nathan

**Comment by PetrusVermaak** [comment]
I did not create it but I use this:
https://csharpsoftwareza.blogspot.com/2020/11/movie-profanity-remover-20.html

**Comment by cybernate321** [comment]
Thanks for your suggestion. I’m playing with it now. 
Do you think it is possible to create something that can mute profanity from streaming platforms rather than needing to have the video file on the computer?

I’ve just seen a video on youtube showing you can use python to mute the master volume.

Regards

Nathan



Sent from Mail for Windows

**Comment by PetrusVermaak** [comment]
I'm sure it's possible, and I've seen it done on Kodi. That is why I asked for it on Plex. But I'm not a coder, so I cannot do it myself. Someone else would need to do it, and as Plex have removed all plugins, the Plex team needs to add it. Unfortunately, they don't see it as a required feature.

**Comment by cybernate321** [comment]
Thanks I’ve just come across this browser plug-in which claims to mute audio on streaming sites. So I’ll have a play around with it. FrostCo/AdvancedProfanityFilter: A browser extension to filter profanity from webpagesgithub.comSent from my iPhoneOn 15 Jun 2023, at 10:36, PetrusVermaak ***@***.***> wrote:﻿
I'm sure it's possible, and I've seen it done on Kodi. That is why I asked for it on Plex. But I'm not a coder, so I cannot do it myself. Someone else would need to do it, and as Plex have removed all plugins, the Plex team needs to add it. Unfortunately, they don't see it as a required feature.

**Comment by PetrusVermaak** [comment]
Thanks! Will check it out!
