### ISSUE TITLE
Make the .edl CMX 3600 Format for Compatibility

### ISSUE THREAD

**Issue by Drive4Code** [mmguero/cleanvid#16]
Due to the audio artifacts still being there, i've been trying to find a way to solve the problem by bypassing ffmpeg. The problem is that by using the `--edl` flag the file generated is only compatible with MPlayer and Kodi, as it is different from the standard.

If the edl was in format CMX 3600, I would be able to import it in a video editor to apply the changes by bypassing ffmpeg

**Comment by mmguero** [comment]
Thanks for the suggestion. I haven't had time to work on this project much lately but I hope to be able to carve out some time in the next few weeks and implement this as well as look at the audio artifacts issue you reported.

**Comment by Drive4Code** [comment]
Thank You for the amazing project. Looking forward to being able to work with it again

**Comment by mmguero** [comment]
I don't see myself finding time for this feature. You're welcome to submit a PR (allowing one to specify CMX vs. mplayer format for the EDL file) if it's important to you.
