### ISSUE TITLE
Timestamp inaccuracy

### ISSUE THREAD

**Issue by Drive4Code** [mmguero/cleanvid#17]
After the update, the video gets muted for too long. After the swear word they work well, but before you get to it consistent issues arise. 
Here's an visualization of the issue:
![image](https://github.com/mmguero/cleanvid/assets/129603940/de81b3bf-9135-44b2-a60c-0c23d9905eec)

My srt files at this point contains the following:
212
00:00:58,680 --> 00:00:58,700
a

213
00:00:58,700 --> 00:00:58,720
fuck.

214
00:00:58,720 --> 00:00:59,300
You're

215
00:00:59,300 --> 00:00:59,360
a

216
00:00:59,360 --> 00:00:59,620
fucking

217
00:00:59,620 --> 00:00:59,680
liar.

**Comment by mmguero** [comment]
Thank you! Looks like I need to adjust the lead in to the mute.

**Comment by mmguero** [comment]
Try the latest release out. I had set the default "padding" around the profanity to 1 second, I've set it back to 0, it can be adjusted with the command-line.

**Comment by Drive4Code** [comment]
I've always had padding set to zero from the command-line. Looks like it's working now though!
