### ISSUE TITLE
Embedded & Burned Subtitles are Incorrect

### ISSUE THREAD

**Issue by Drive4Code** [mmguero/cleanvid#19]
I've noticed that the subs when running the `--burn` and `--embed-subs` flags are the ones of the words_clean.srt rather than the cleaned original subtitles. This means the only thing displayed is ***** or replacement words where the profanity's been muted, rather than the original file's subtitle with the censored words

**Comment by mmguero** [comment]
If you include the flag `-f`/`--full-subs` you get the full subtitles, right? If so, that is working as intended.

**Comment by Drive4Code** [comment]
You're right, thank you! Love the padding update as well that's been doing wonders
