### ISSUE TITLE
--plex-auto-skip-json is not generating anything

### ISSUE THREAD

**Issue by elmateo487** [mmguero/cleanvid#22]
Consider the following command, I am unable to get cleanvid to generate auto skip json

`cleanvid -i "/example/Oppenheimer (2023) (2160p).mkv" --plex-auto-skip-json /Users/Example/Desktop/json.json --plex-auto-skip-id 66558 -w /Users/Example/Desktop/wordfilters.txt -s "/Users/Example/Downloads/oppenheimer.srt"`

I can get it to create a video mkv file if I set an output AND designate -e. But I cannot get the tool to create the json file for plex-auto-skip

With that said, I really appreciate you supporting this, and included plex-auto-skip in this. Let me know what other info you need.

**Comment by mmguero** [comment]
Hmm, it seems to work for me:

```
$ cleanvid -i Terminator\ 1\ 1984.mp4 \
  --plex-auto-skip-json Terminator\ 1\ 1984.json \
  --plex-auto-skip-id 66558 \
  -w ~/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/cleanvid/swears.txt \
  -s Terminator\ 1\ 1984.srt

$ ls -l ls -l Terminator\ 1\ 1984*
-rw-r--r-- 1 tlacuache tlacuache       1,773 Nov 21 20:27 'Terminator 1 1984_clean.srt'
-rw-r--r-- 1 tlacuache tlacuache       4,025 Nov 21 20:27 'Terminator 1 1984.json'
-rw-r--r-- 1 tlacuache tlacuache 683,425,407 Sep 21 15:43 'Terminator 1 1984.mp4'
-rw-r--r-- 1 tlacuache tlacuache      68,173 Nov 21 18:28 'Terminator 1 1984.srt'
```

Does it consistently break with other files you've tried? Your wordfilters.txt file looks valid?
