### ISSUE TITLE
--swears

### ISSUE THREAD

**Issue by akeslo** [mmguero/cleanvid#23]
I must be doing something wrong. -w / --swears doesn't seem to allow me to use my own swears.txt file.

**Comment by mmguero** [comment]
Thanks for the heads-up, I'll take a look.

**Comment by mmguero** [comment]
I can't reproduce it. What platform are you on (Windows? Linux? macOS?)? What's the exact command you're running? If you try to give it a filename that doesn't exist do you get an error or does it behave the same?

For me:

```
$ cleanvid -i Rick.and.Morty.S07E01.mkv \
                 -s Rick.and.Morty.S07E01.2.eng.srt \
                 -w /home/user/Desktop/swears.txt \
                 -f --subs-only
```

returns no error. I made sure it was using my defined swears.txt file as well by removing all entries in it except one and then testing for just that one.
