### ISSUE TITLE
GUI or Plugin Support coming?

### ISSUE THREAD

**Issue by Zacharybinx34** [mmguero/cleanvid#24]
Would be really nice to have plugin support for Kodi/Jellyfin, Emby, or Plex. 
Any plans to add this, or just create a basic GUI to make running this easier?

**Comment by mmguero** [comment]
Currently I don't have time to dedicate to this, but thanks for the suggestion. I'll keep it in mind for when my schedule gets a little less crazy.

**Comment by mmguero** [comment]
closing as not planned. would accept a PR of course.
