### ISSUE TITLE
-f output

### ISSUE THREAD

**Issue by akeslo** [mmguero/cleanvid#29]
Is it possible to have the subtitles output with multiple words per line instead of 1 word per timestamp?

<img width="252" alt="image" src="https://github.com/mmguero/cleanvid/assets/3003773/dce3a302-4b93-4089-b347-2cfd229c1b59">

**Comment by mmguero** [comment]
What does the original subtitle file look like? I don't think cleanvid can even do what you're seeing there, unless it was like that to begin with. sleanvid edits the subtitles "in place" without changing the existing timings or groupings of the words.

**Comment by akeslo** [comment]
You are right, sorry! :). Thanks for the help.  This was coming from an SRT I was generating first from whisper_timestamp that had that format.
