### ISSUE TITLE
Utilizing more than 1 thread

### ISSUE THREAD

**Issue by bradyj04** [mmguero/cleanvid#30]
OS: Linux (in a docker container to be specific)

Is there a way to have this script utilize more than 1 thread, I have some other ffmpeg stuff that runs and is able to use more which speeds it up considerably, is that not possible in this because of some restriction?
If so, is there a way to pass the -threads flag to ffmpeg through cleanvid?
Please let me know, thanks.

**Comment by mmguero** [comment]
Should be addressed in v1.5.7
