### ISSUE TITLE
Audio changes

### ISSUE THREAD

**Issue by bradyj04** [mmguero/cleanvid#31]
Is it possible to modify the audio track of the video passed in and use a filter to boost it by a certain amount of db like in ffmpeg normally? I noticed there is a section for audio parameters for it but it only seems to execute if it is reencoding.
Please let me know thanks.

**Comment by mmguero** [comment]
I'll add an option for `--re-encode-audio` to force audio encoding regardless of whether or not it's muting the subs. Then you should be able to put what other audio parameters/filters in the `--audio-params` argument and have it take effect.

**Comment by mmguero** [comment]
Should be addressed in v1.5.7
