### ISSUE TITLE
Randomly missing swears that appear in the srt

### ISSUE THREAD

**Issue by bradyj04** [mmguero/cleanvid#34]
It properly transcribes the srt and even says it was removed in the cleaned srt, but the audio is not muted. Any ideas why? I haven't seen any errors regarding it, and other words are properly muted, but not the first one usually.
Thanks for any help!

**Comment by mmguero** [comment]
Release v1.6.0 fixes an issue (#32) with the *last* entry not being muted (even though it appeared ****-ed in the srt), but I haven't seen it with earlier entries having the problem. Would you try that and if you still have that problem reply here and, if you can, attach an srt file that causes the issue?

**Comment by mmguero** [comment]
I believe this was fixed in the last release, please reopen if it's still causing a problem for you
