### ISSUE TITLE
Can't figure this out

### ISSUE THREAD

**Issue by Zacharybinx34** [mmguero/cleanvid#39]
I have it installed, but I can't get Mplayer to work, and have no clue how to get this working with Kodi. 

Do you have any more specific/detailed instructions explaining how to use this on top of video files? I don't want to make new video files if I don't have to.

**Comment by mmguero** [comment]
This project is only for generating new video files, it does not work on-the-fly in a media player with existing files in place. 

After installing cleanvid, you run it on the command line as described in the readme that's on the front page of this repository. For example, something like this:

```
cleanvid --input whatever.mp4 --subs whatever.srt --full-subs --pad 1 --embed-subs
```

Just depending on what you want to do with the file.
