### ISSUE TITLE
Possible inclusion of a range flag / option?

### ISSUE THREAD

**Issue by katanaBadger** [mmguero/cleanvid#4]
Hello!
Firstly, I wanted to thank you for making this neat program, I really appreciate it and it's been a wonderful help for me!

For this Issue / Suggestion, I'd like to enquire about a range option or help with a line of code in the script if even possible, basically, like some other profanity muters there's an option to set a before and after extension on the found lines from the subtitle, so that in the event of a sudden exclamation by a speaker, slightly offset timing, or trailing swears, this would ensure that they're caught by the volume mute by starting a little early (usually 500ms) and ending a little later (also 500ms) on top of the duration of the line, like so:
 
![image](https://user-images.githubusercontent.com/70804282/105634904-01d14100-5e69-11eb-8684-a3a169a213a8.png)

Any assistance would be wonderful!
Thank you again

**Comment by mmguero** [comment]
I've pushed up a commit (sorry it took me so long to get around to it). Let me know how it works for you!
