### ISSUE TITLE
Offline mode?

### ISSUE THREAD

**Issue by hendursaga** [mmguero/cleanvid#6]
From the README: "If subtitles are not provided explicitly, they will be extracted from the video file if possible; if not, [subliminal](https://github.com/Diaoul/subliminal) is used to attempt to download the best matching .srt file."

It would be a nice idea to include some flag where `cleanvid` would never need Internet access or otherwise call out to whatever various servers `subliminal` uses.

**Comment by mmguero** [comment]
Great idea, thanks. Actually lately I've been noticing subliminal hasn't been working very consistently. So this would be good anyway.
