### ISSUE TITLE
Add the ability to insert time codes and have cleanvid make cuts

### ISSUE THREAD

**Issue by orangehulk** [mmguero/cleanvid#7]
CleanVid works great! I appreciate the work. I'd love the ability to also provide a file with time codes and have cleanvid cut the video, kind of like what Vidangel does, but open source of course. If I had the skills I'd love to try making it, but my coding is very limited.

**Comment by mmguero** [comment]
Thanks for the idea. In the meantime, I personally use [lossless-cut](https://github.com/mifi/lossless-cut) to do kind of what you're talking about. It works very well.

**Comment by orangehulk** [comment]
I will take a look. Thanks!

**Comment by vendova** [comment]
> Thanks for the idea. In the meantime, I personally use [lossless-cut](https://github.com/mifi/lossless-cut) to do kind of what you're talking about. It works very well.

Can you please suggest me wiki on how to use this being a GitHub newbie or a youtube video tutorial on how to use this to mute the profanity in movie file. Thanks and cheers

**Comment by hendursaga** [comment]
> kind of like what Vidangel does, but open source

Cleanvid already does this...? To keep within US laws, Vidangel doesn't tamper with the original files. With MPlayer and the `--edl` option, you can replicate that behavior.

**Comment by mmguero** [comment]
I think beyond the EDL stuff and suggestions for other tools like losslesscut, I'm going to consider this outside the scope of what I've got time to implement in cleanvid. Thanks for the suggestion, though.
